name: Test & Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run Tests with Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator \
          -reports:**/coverage.cobertura.xml \
          -targetdir:coveragereport \
          -reporttypes:Html

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: coveragereport
